<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SpaRoot>..\angularbiblereader.client</SpaRoot>
    <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:63651</SpaProxyServerUrl>
    <UserSecretsId>643d98b5-03b0-44c7-bd36-482d89f91b13</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>10.*-*</Version>
    </PackageReference>
    <PackageReference Include="BiblePlatform.API" Version="0.1.2-alpha.0.16" />
    <PackageReference Include="BiblePlatform.API.Models" Version="0.1.2-alpha.0.16" />
    <PackageReference Include="BiblePlatform.SDK.Services" Version="0.1.2-alpha.0.16" />
    <PackageReference Include="BiblePlatform.UsfmReferences" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\angularbiblereader.client\angularbiblereader.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

</Project>
